xray_compose_project_name: xray-vpn
xray_container_name: xray-vpn
xray_image_tag: "25.12.8"

xray_log_level: warning
xray_server_address: "{{ ansible_host }}"

xray_vless_port: 8443
xray_reality_dest: www.cloudflare.com:443
xray_reality_server_name: www.cloudflare.com

xray_telegram_socks_port: 29418

xray_client_uuid: ""
xray_reality_private_key: ""
xray_reality_short_id: ""
xray_telegram_socks_user: ""
xray_telegram_socks_pass: ""

xray_env_extra: {}

tuic_project_root: /opt/tuic-vpn
tuic_deploy_user: root
tuic_deploy_group: root
tuic_compose_project_name: tuic-vpn
tuic_container_name: sing-box-tuic
singbox_image_tag: "v1.13.8"
tuic_pull_image: true
tuic_run_validate: true
tuic_log_level: warning
tuic_server_address: "{{ ansible_host }}"
tuic_port: 443
tuic_uuid: ""
tuic_password: ""
tuic_shadowrocket_allow_insecure: 1
tuic_shadowrocket_name: tuic-vpn
tuic_sysctl_rmem_max: "26214400"
tuic_sysctl_wmem_max: "26214400"
tuic_sysctl_rmem_default: "1048576"
tuic_sysctl_wmem_default: "1048576"
tuic_sysctl_udp_rmem_min: "65536"
tuic_sysctl_udp_wmem_min: "65536"
tuic_env_extra: {}
